version: '3'
services:
  raccoon:
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: on-failure
    ports:
      - "4123:80"
    volumes:
      - ../RaccoonWP:/raccoon
      - db_data:/var/lib/mysql
    environment:
      DB_HOST: localhost
      DB_NAME: ${MYSQL_DATABASE}
      DB_USER: ${MYSQL_USER}
      DB_PASSWORD: ${MYSQL_PASSWORD}
      WP_ENV: development
      WP_HOME: http://localhost:4123
volumes:
  db_data: